version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/code/
    ports:
      - "5000:5000"
    links:
      - postgresql
    environment:
      - PORT=5000
  postgresql:
    image: postgres:10.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
